
export const dataTooltips: Record<string, string> = {
  // EPC
  address1: 'Address line 1.',
  address2: 'Address line 2.',
  address3: 'Address line 3.',
  posttown: 'The post town of the property.',
  postcode: 'The postcode of the property.',
  county: 'The county of the property.',
  lodgementDate: 'Date on which the certificate was lodged on the register.',
  inspectionDate: 'Date of the EPC inspection.',
  rating: 'The energy rating of the property, from A to G.',
  potentialRating: 'The potential energy rating of the property, from A to G.',
  currentEnergyEfficiency: 'A measure of the property’s current overall energy efficiency. The higher the rating the more energy efficient the home is and the lower the fuel bills are likely to be.',
  potentialEnergyEfficiency: 'The potential energy efficiency of the property.',
  propertyType: 'The type of property.',
  builtForm: 'The built form of the property.',
  constructionAgeBand: 'The age band of the property.',
  tenure: 'Tenure of property.',
  uprn: 'Unique Property Reference Number.',
  buildingReferenceNumber: 'The reference number for the building.',
  localAuthorityLabel: 'The name of the local authority.',
  constituencyLabel: 'The name of the constituency.',
  totalFloorArea: 'The total floor area of the property, in square metres.',
  numberHabitableRooms: 'The number of habitable rooms in the property.',
  numberHeatedRooms: 'The number of heated rooms in the property.',
  transactionType: 'The transaction type of the property.',
  mainHeatDescription: 'A description of the main heating system.',
  mainheatcontDescription: 'A description of the main heating controls.',
  mainFuel: 'The main fuel used for heating the property.',
  secondheatDescription: 'A description of the secondary heating system.',
  hotwaterDescription: 'A description of the hot water system.',
  wallsDescription: 'A description of the walls.',
  wallsEnergyEff: 'The energy efficiency of the walls.',
  roofDescription: 'A description of the roof.',
  roofEnergyEff: 'The energy efficiency of the roof.',
  floorDescription: 'A description of the floor.',
  windowsDescription: 'A description of the windows.',
  windowsEnergyEff: 'The energy efficiency of the windows.',
  lightingDescription: 'A description of the lighting.',
  lightingEnergyEff: 'The energy efficiency of the lighting.',
  co2EmissionsCurrent: 'The current carbon dioxide emissions of the property.',
  co2EmissionsPotential: 'The potential carbon dioxide emissions of the property.',
  energyConsumptionCurrent: 'The current energy consumption of the property.',
  energyConsumptionPotential: 'The potential energy consumption of the property.',
  heatingCostCurrent: 'The current heating cost of the property.',
  heatingCostPotential: 'The potential heating cost of the property.',
  hotWaterCostCurrent: 'The current hot water cost of the property.',
  hotWaterCostPotential: 'The potential hot water cost of the property.',
  lightingCostCurrent: 'The current lighting cost of the property.',
  lightingCostPotential: 'The potential lighting cost of the property.',
  // Flood Risk
  PROB_4BAND: 'Likelihood of flooding from rivers and sea. High: >3.3%, Medium: 1%-3.3%, Low: 0.1%-1%, Very Low: <0.1%.',
  SUITABILITY: 'The scale at which it is suitable to use the likelihood information.',
  PUB_DATE: 'Date (financial quarter) of publication of the flood risk data.',
  easting: 'Along with northing defines the point within the postcode used to match a flood risk area.',
  northing: 'Along with easting defines the point within the postcode used to match a flood risk area.',
  latitude: 'Along with longitude defines the point within the postcode used to match a flood risk area.',
  longitude: 'Along with latitude defines the point within the postcode used to match a flood risk area.',
  // New EPC Fields
  lowEnergyFixedLightCount: 'The number of low-energy fixed lights.',
  uprnSource: 'The source of the UPRN.',
  floorHeight: 'The average height of the storeys, in metres.',
  mainheatEnergyEff: 'The energy efficiency of the main heating system.',
  windowsEnvEff: 'The environmental efficiency of the windows.',
  lightingEnvEff: 'The environmental efficiency of the lighting.',
  environmentImpactPotential: 'A measure of a home’s impact on the environment in terms of carbon dioxide (CO2) emissions. The higher the rating the less impact it has on the environment.',
  glazedType: 'The type of glazing.',
  sheatingEnergyEff: 'The energy efficiency of the sheating.',
  fixedLightingOutletsCount: 'The total number of fixed lighting outlets.',
  solarWaterHeatingFlag: 'Indicates if solar water heating is present.',
  constituency: 'The constituency ID.',
  localAuthority: 'The local authority ID.',
  numberOpenFireplaces: 'The number of open fireplaces.',
  glazedArea: 'The glazed area of the property.',
  heatLossCorridor: 'Heat loss corridor.',
  flatStoreyCount: 'The number of storeys in the flat.',
  roofEnvEff: 'The environmental efficiency of the roof.',
  environmentImpactCurrent: 'A measure of a home’s impact on the environment in terms of carbon dioxide (CO2) emissions. The higher the rating the less impact it has on the environment.',
  floorEnergyEff: 'The energy efficiency of the floor.',
  hotWaterEnvEff: 'The environmental efficiency of the hot water system.',
  mainheatcEnergyEff: 'The energy efficiency of the main heating controls.',
  wallsEnvEff: 'The environmental efficiency of the walls.',
  photoSupply: 'The photo supply.',
  mainheatEnvEff: 'The environmental efficiency of the main heating system.',
  lodgementDatetime: 'The date and time the certificate was lodged.',
  flatTopStorey: 'Indicates if the flat is on the top storey.',
  extensionCount: 'The number of extensions.',
  mainheatcEnvEff: 'The environmental efficiency of the main heating controls.',
  lmkKey: 'The LMK key for the certificate.',
  windTurbineCount: 'The number of wind turbines.',
  floorLevel: 'The floor level of the property.',
  multiGlazeProportion: 'The proportion of multi-glazing.',
  lowEnergyLighting: 'The percentage of low-energy lighting.',
  mainHeatingControls: 'The main heating controls code.',
  mechanicalVentilation: 'The type of mechanical ventilation.',
  co2EmissCurrPerFloorArea: 'CO2 emissions per square metre of floor area.',
  mainsGasFlag: 'Indicates if mains gas is available.',
  energyTariff: 'The energy tariff.',
  reportType: 'The type of report.',
};
