import { PropertyDocument } from './types';

export const DEFAULT_DOCUMENTS: PropertyDocument[] = [
  {
    id: 'epc',
    name: 'Energy Performance Certificate (EPC)',
    description: 'A certificate showing the energy efficiency of the property.',
    status: 'missing',
    category: 'technical',
    required: true,
  },
  {
    id: 'index',
    name: 'Index of Documents',
    description: 'A list of all documents included in the pack.',
    status: 'pending',
    category: 'legal',
    required: true,
  },
  {
    id: 'sale-statement',
    name: 'Sale Statement',
    description: 'Basic information about the property and its ownership.',
    status: 'missing',
    category: 'legal',
    required: true,
  },
  {
    id: 'title-deeds',
    name: 'Land Registry Title Deeds',
    description: 'Official documents proving ownership and property boundaries.',
    status: 'missing',
    category: 'legal',
    required: true,
  },
  {
    id: 'local-search',
    name: 'Local Authority Search',
    description: 'Information about planning, highways, and other local matters.',
    status: 'missing',
    category: 'local',
    required: false,
  },
  {
    id: 'drainage-search',
    name: 'Drainage and Water Search',
    description: 'Confirmation of water supply and sewer connections.',
    status: 'missing',
    category: 'local',
    required: false,
  },
  {
    id: 'ta6',
    name: 'Property Information Form (TA6)',
    description: 'Detailed information about the property provided by the seller.',
    status: 'missing',
    category: 'legal',
    required: true,
  },
  {
    id: 'ta10',
    name: 'Fittings and Contents Form (TA10)',
    description: 'A list of what is included in the sale (e.g., carpets, curtains).',
    status: 'missing',
    category: 'legal',
    required: true,
  },
  {
    id: 'leasehold-info',
    name: 'Leasehold Information Pack',
    description: 'Required if the property is leasehold.',
    status: 'not-applicable',
    category: 'legal',
    required: false,
  },
  {
    id: 'planning',
    name: 'Planning & Building Regulations',
    description: 'Copies of permissions for any works carried out.',
    status: 'missing',
    category: 'technical',
    required: false,
  },
];
